from $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION

# Setting timezone to IST
ENV TZ=Asia/Kolkata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY lib-$DOCKER_IMAGE lib
RUN $BUILD_COMMAND

# Copy GCP Service Account keyfile
COPY keyfile.json /usr/src/app/keyfile.json

# Setting environment variables
ENV REALM=$REALM
ENV STAGE=$STAGE
ENV AWS_PROJ_ID=$AWS_PROJ_ID
ENV GCP_PROJ_ID=$GCP_PROJ_ID
ENV API_END_POINT=$API_END_POINT
ENV GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/keyfile.json
